### ISSUE TITLE
tck compatibility with sightly spec

### ISSUE THREAD

**Issue by kevinpeno** [Adobe-Marketing-Cloud/sightly-tck#15]
I'm planning on a js implementation of sightly to facilitate a front-end workflow and wanted to confirm, is this TCK up to date with the sightly 1.1 spec? From the tickets that have been closed (at brief glance) it appears it may be, but the readme only appears to reference 1.0.

If it is, could we please get some tagged releases tied to sightly versions for easy reference?

Thanks!

**Comment by raducotescu** [comment]
@kevinpeno, I just updated the README in 5561a45 to point to the `1.2.1` release of the TCK which is compatible with the 1.2 version [0] of the specification.

[0] - https://github.com/Adobe-Marketing-Cloud/sightly-spec/blob/1.2/SPECIFICATION.md

**Comment by kevinpeno** [comment]
Thanks!
